### ISSUE TITLE
Implement a Crazyflie swift object

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie2-ios-client#10]
To start implementing Log and Param it would be beneficial to encapsulate the Crazyflie connection and operation in a Crazyflie object. This will have at least 2 advantage:
- Simplify implementation of new Crazyflie functionality and clean-up the high-level loops by having clear API (ie we will be able to write something like "cflie.sendCommander(roll, pitch, yaw, thrust)" instead of the current packing in the viewController)
- It almost become a swift Crazyflie lib which would allow implementation of Mac OS-X clients, and if the link is abstracted it will work with Crazyradio on Mac

**Comment by EMart002** [comment]
This issue can be closed because it is covered in #12

**Comment by ataffanel** [comment]
Agreed, closing.
