### ISSUE TITLE
RFC: Convert the full app to Swift

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie2-ios-client#12]
This is a request for comment, I am not experienced enough in iOS development to really have an opinion on that.

The Crazyflie iOS client has been started the same month Swift was announced so it felt risky starting directly in Swift (and no tutorial where updated yet). However nowadays I feel more confortable coding in Swift.

So the question is: is there any interest in converting the app in Swift and does anyone has an idea of the complexity of the task? There is not much left in objective-C but it is the central part (the view controllers).

**Comment by EMart002** [comment]
Hi @ataffanel, just to let you know, i'm currently working on the swift3 issues #12 and #10

**Comment by ataffanel** [comment]
Hi @EMart002, sounds good thanks for the heads up! Tell me if you hit any problem I can help with.

**Comment by EMart002** [comment]
Hi @ataffanel, i think i'll be done tonight with the implementation in swift. Thereafter i'll create a pull request. One thing: i ususally fly the crazyflie with both blue leds facing to me. Am i doing it correct? This is an important information for me so i can test it the correct way :)

**Comment by ataffanel** [comment]
Yes, the two blue LED are on the back of the Crazyflie, so they should be facing you when flying.

That is good news, I look forward to testing it!

**Comment by ataffanel** [comment]
Mostly implemented thanks to @EMart002. The only part left is to find a way to pack/unpack the binary radio packets in swift.

**Comment by valeriyvan** [comment]
With #33 all app is Swift now.
I think this issue could be closed as implemented.

**Comment by ataffanel** [comment]
This is correct, I can close the issue. Thanks for the help!
