### ISSUE TITLE
iphone8 plus thrust fail, only two motor ok

### ISSUE THREAD

**Issue by xingqing6210** [bitcraze/crazyflie2-ios-client#22]
iphone8 plus thrust fail, only two motor ok

**Comment by justinleeyang** [comment]
hi, 

xingqing6210 is also my account.

we use the newest 2018.10 release firmware. The hardware crazyflie2.0 hove no problem, because I already use the crazyradio and android app to fly it normally. but ios app fail. when push thrust, the crazyflie2.0 only two motors work. other no any drive.

**Comment by ataffanel** [comment]
I have not been able to reproduce the problem using an iphone 6S, the latest release of the ios client and a Crazyflie running 2018.10.

Can you try to reset all the settings and test on another iphone to find out where the problem could be?
