### ISSUE TITLE
Feature: Motion Control

### ISSUE THREAD

**Issue by EMart002** [bitcraze/crazyflie2-ios-client#5]
Hi, i've worked on a motion control feature for the crazy fly iOS Client and i'd really like to contribute my feature-branch here. Could you @ataffanel pls give my access for the contribution. Hope you guys'll like it :)
Best
Martin

**Comment by ataffanel** [comment]
Hi, sounds great! We accepts contributions via pull requests. Could you send us a pull requests with the commits?

**Comment by EMart002** [comment]
Thanks. Pull request sent. If something is missing or unclear, pls do not hesitate to ask.
